version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hello

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
